spring:
  application:
    name: Delivery
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=delivery;encrypt=true;trustServerCertificate=true
    username: SA
    password: yourStrong(!)Password
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true